# openapi2-functions.yaml
swagger: '2.0'
info:
  title: scareflix-cat api
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /all-videos:
    get:
      summary: Get a list of videos in the catalog
      operationId: all_videos
      x-google-backend:
        address: https://europe-west1-scareflix.cloudfunctions.net/scareflix-cat-api-videos-function
      responses:
        '200':
          description: A successful response
          schema:
            type: string